---
title: "p8105_hw6_cw3370.Rmd"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(knitr)
```

# Problem 1
```{r message=FALSE}
birthweight_df <- read_csv("data/birthweight.csv") %>% 
  mutate(
    babysex = factor(babysex,
                     levels = c(1,2),
                     labels = c("male","female")),
    frace = factor(frace,
                   levels = c(1,2,3,4,8,9),
                   labels = c("White","Black","Asian","Puerto Rican","Other","Unkown")),
    malform = factor(malform,
                     levels = c(0,1),
                     labels = c("absense","present")),
    mrace = factor(mrace,
               levels = c(1,2,3,4,8),
               labels = c("White","Black","Asian","Puerto Rican","Other"))
) %>% 
  drop_na()

```

based on knowledge for the factors that underly birthweight, l choose several factors, including: bhead,blength,frace,malform,mrace,ppwt,wtgain,smoken and then l make  plots and conduct SLR of birthweight versus each factor to see whether there are potential relationship(checking plot and R^2).Finally l choose bhead and blength.
```{r eval = FALSE,echo=FALSE}
#
birthweight_df %>% 
  ggplot(aes(x = bhead, y = bwt)) +
  geom_point()

lm(bwt ~ bhead, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)

#
birthweight_df %>% 
  ggplot(aes(x = blength, y = bwt)) +
  geom_point()

lm(bwt ~ blength, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)
#
birthweight_df %>% 
  ggplot(aes(x = frace, y = bwt)) +
  geom_violin()

lm(bwt ~ frace, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)
#
birthweight_df %>% 
  ggplot(aes(x = malform, y = bwt)) +
  geom_violin()

lm(bwt ~ malform, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)
#
birthweight_df %>% 
  ggplot(aes(x = mrace, y = bwt)) +
  geom_violin()

lm(bwt ~ mrace, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)
#
birthweight_df %>% 
  ggplot(aes(x = ppwt, y = bwt)) +
  geom_point()

lm(bwt ~ ppwt, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)
#
birthweight_df %>% 
  ggplot(aes(x = wtgain, y = bwt)) +
  geom_point()



lm(bwt ~ wtgain, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)
#
birthweight_df %>% 
  ggplot(aes(x = smoken, y = bwt)) +
  geom_point()

lm(bwt ~ smoken, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)
```

```{r echo=FALSE}
test <- 
tibble(
  variable = c("bhead","blength","frace","malform","mrace","ppwt","wtgain","smoken"),
  R_squared = c(
lm(bwt ~ bhead, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared),
lm(bwt ~ blength, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared),
lm(bwt ~ frace, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared),
lm(bwt ~ malform, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared),
lm(bwt ~ mrace, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared),
lm(bwt ~ ppwt, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared),
lm(bwt ~ wtgain, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared),
lm(bwt ~ smoken, data = birthweight_df) %>% 
   broom::glance() %>% 
   pull(r.squared)))

knitr::kable(test)
```
